-- MySQL Script generated by MySQL Workbench
-- Fri Mar  1 19:37:30 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Fabrikat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fabrikat` (
  `id_fabrikat` INT NOT NULL,
  `fabrikat` VARCHAR(45) NULL,
  PRIMARY KEY (`id_fabrikat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Typ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Typ` (
  `id_typ` INT NOT NULL AUTO_INCREMENT,
  `machinentyp` VARCHAR(45) NULL,
  PRIMARY KEY (`id_typ`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Machine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Machine` (
  `id_machine` INT NOT NULL AUTO_INCREMENT,
  `ref_id_typ` INT NULL,
  `ref_id_fabrikat` INT NULL,
  `ref_id_zusatz` INT NULL,
  `ref_id_vermietung` INT NULL,
  `gewicht` INT NULL,
  PRIMARY KEY (`id_machine`),
  INDEX `fk_machine_fabrikat_idx` (`ref_id_fabrikat` ASC) VISIBLE,
  INDEX `fk_machine_typ_idx` (`ref_id_typ` ASC) VISIBLE,
  CONSTRAINT `fk_machine_fabrikat`
    FOREIGN KEY (`ref_id_fabrikat`)
    REFERENCES `mydb`.`Fabrikat` (`id_fabrikat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_machine_typ`
    FOREIGN KEY (`ref_id_typ`)
    REFERENCES `mydb`.`Typ` (`id_typ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kunde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kunde` (
  `id_kunde` INT NOT NULL,
  `kundenname` VARCHAR(45) NULL,
  PRIMARY KEY (`id_kunde`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mietdauer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mietdauer` (
  `id_mietdauer` INT NOT NULL AUTO_INCREMENT,
  `von` DATE NULL,
  `bis` DATE NULL,
  PRIMARY KEY (`id_mietdauer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vermietung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vermietung` (
  `id_vermietung` INT NOT NULL,
  `ref_id_machine` INT NULL,
  `ref_id_mietdauer` INT NULL,
  `ref_id_kunde` INT NULL,
  PRIMARY KEY (`id_vermietung`),
  INDEX `fk_vermietung_machine_idx` (`ref_id_machine` ASC) VISIBLE,
  INDEX `fk_vermietung_kunde_idx` (`ref_id_kunde` ASC) VISIBLE,
  INDEX `fk_vermietung_dauer_idx` (`ref_id_mietdauer` ASC) VISIBLE,
  CONSTRAINT `fk_vermietung_machine`
    FOREIGN KEY (`ref_id_machine`)
    REFERENCES `mydb`.`Machine` (`id_machine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vermietung_kunde`
    FOREIGN KEY (`ref_id_kunde`)
    REFERENCES `mydb`.`Kunde` (`id_kunde`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vermietung_dauer`
    FOREIGN KEY (`ref_id_mietdauer`)
    REFERENCES `mydb`.`Mietdauer` (`id_mietdauer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
